USE ROLE IDENTIFIER('{{ target_role_name }}');
USE WAREHOUSE IDENTIFIER('{{ target_warehouse_name }}');

USE DATABASE IDENTIFIER('{{ target_database_name }}');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('{{ target_schema_name }}') WITH MANAGED ACCESS;
USE SCHEMA INFORMATION_SCHEMA;
DROP SCHEMA IF EXISTS PUBLIC;
USE SCHEMA IDENTIFIER('{{ target_schema_name }}');

CREATE TABLE IF NOT EXISTS TEST_TABLE (
    COL1 VARCHAR,
    COL2 INTEGER
);